---
- name: despliegue del c√≥dgi html
  file:
    src: /home/vagrant/fhw-ivanchover-ud10-roles/index-{{ env }}.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data

    
...
